trigger:
 tags:
    include:
    - release*

pool:
  vmImage: ubuntu-latest
  
variables:
- group: pipeline

steps:

 - checkout: self

 - script: dotnet build dotnet --configuration release
   displayName: 'Build All Projects'

 - script: dotnet test dotnet/ADP.VINDecode.Tests
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-dotnet'))
   displayName: 'Test ADP.VINDecode'

 - script: dotnet pack dotnet/ADP.VINDecode --configuration Release --output $(Build.ArtifactStagingDirectory)
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-dotnet')) 
   displayName: 'pack ADP.VINDecode'

 - task: NuGetToolInstaller@1
   inputs:
    versionSpec: '6.9.1'

 - task: NuGetCommand@2
   displayName: 'Push ADP.VINDecode dotnet Packages'
   condition: or(contains(variables['Build.SourceBranch'], 'refs/tags/release-all'), contains(variables['Build.SourceBranch'], 'refs/tags/release-dotnet'))
   inputs:
    command: 'custom'
    arguments: 'push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" -Source https://api.nuget.org/v3/index.json -ApiKey $(ShiftSoftwareNugetApiKey) -SkipDuplicate'